In [12]:
import numpy as np

np.set_printoptions(threshold=10)

In [13]:
fish_length = [25.4, 26.3, 26.5, 29.0, 29.0, 29.7, 29.7, 30.0, 30.0, 30.7, 31.0, 31.0, 
                31.5, 32.0, 32.0, 32.0, 33.0, 33.0, 33.5, 33.5, 34.0, 34.0, 34.5, 35.0, 
                35.0, 35.0, 35.0, 36.0, 36.0, 37.0, 38.5, 38.5, 39.5, 41.0, 41.0, 9.8, 
                10.5, 10.6, 11.0, 11.2, 11.3, 11.8, 11.8, 12.0, 12.2, 12.4, 13.0, 14.3, 15.0]
fish_weight = [242.0, 290.0, 340.0, 363.0, 430.0, 450.0, 500.0, 390.0, 450.0, 500.0, 475.0, 500.0, 
                500.0, 340.0, 600.0, 600.0, 700.0, 700.0, 610.0, 650.0, 575.0, 685.0, 620.0, 680.0, 
                700.0, 725.0, 720.0, 714.0, 850.0, 1000.0, 920.0, 955.0, 925.0, 975.0, 950.0, 6.7, 
                7.5, 7.0, 9.7, 9.8, 8.7, 10.0, 9.9, 9.8, 12.2, 13.4, 12.2, 19.7, 19.9]

In [26]:
# np를 튜플 형식으로 사용기

stack = np.column_stack(([1, 2, 3], [4, 5, 6]))
print(stack)
print()
print(np.ones(5))

[[1 4]
 [2 5]
 [3 6]]

[1. 1. 1. 1. 1.]


In [23]:
fish_data = np.column_stack((fish_length, fish_weight))

print('fish_data:\n',fish_data)

fish_target = np.concatenate((np.ones(35), np.zeros(14)))

print('\nfish_target:')
fish_target

fish_data:
 [[ 25.4 242. ]
 [ 26.3 290. ]
 [ 26.5 340. ]
 ...
 [ 13.   12.2]
 [ 14.3  19.7]
 [ 15.   19.9]]

fish_target:


array([1., 1., 1., ..., 0., 0., 0.])